2024-08-30 20:38:51,216 INFO    StreamThr :14510 [internal.py:wandb_internal():85] W&B internal server running at pid: 14510, started at: 2024-08-30 20:38:51.214448
2024-08-30 20:38:51,217 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status
2024-08-30 20:38:51,229 INFO    WriterThread:14510 [datastore.py:open_for_write():87] open: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/run-d9osfep0.wandb
2024-08-30 20:38:51,229 DEBUG   SenderThread:14510 [sender.py:send():391] send: header
2024-08-30 20:38:51,246 DEBUG   SenderThread:14510 [sender.py:send():391] send: run
2024-08-30 20:38:52,995 INFO    SenderThread:14510 [dir_watcher.py:__init__():211] watching files in: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files
2024-08-30 20:38:52,995 INFO    SenderThread:14510 [sender.py:_start_run_threads():1200] run started: d9osfep0 with start time 1725021531.21574
2024-08-30 20:38:53,016 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: run_start
2024-08-30 20:38:53,029 DEBUG   HandlerThread:14510 [system_info.py:__init__():26] System info init
2024-08-30 20:38:53,029 DEBUG   HandlerThread:14510 [system_info.py:__init__():41] System info init done
2024-08-30 20:38:53,029 INFO    HandlerThread:14510 [system_monitor.py:start():194] Starting system monitor
2024-08-30 20:38:53,029 INFO    SystemMonitor:14510 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-30 20:38:53,029 INFO    HandlerThread:14510 [system_monitor.py:probe():214] Collecting system info
2024-08-30 20:38:53,030 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started cpu monitoring
2024-08-30 20:38:53,034 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started disk monitoring
2024-08-30 20:38:53,038 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started gpuapple monitoring
2024-08-30 20:38:53,040 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started memory monitoring
2024-08-30 20:38:53,041 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started network monitoring
2024-08-30 20:38:53,937 DEBUG   HandlerThread:14510 [system_info.py:probe():152] Probing system
2024-08-30 20:38:53,942 DEBUG   HandlerThread:14510 [gitlib.py:_init_repo():56] git repository is invalid
2024-08-30 20:38:53,942 DEBUG   HandlerThread:14510 [system_info.py:probe():200] Probing system done
2024-08-30 20:38:53,942 DEBUG   HandlerThread:14510 [system_monitor.py:probe():223] {'os': 'macOS-14.5-arm64-arm-64bit', 'python': '3.10.14', 'heartbeatAt': '2024-08-30T12:38:53.937366', 'startedAt': '2024-08-30T12:38:51.203268', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/kaggle.ipynb', 'codePathLocal': None, 'root': '/Users/meinv', 'host': 'TeriMacBook-Pro.local', 'username': 'meinv', 'executable': '/Users/meinv/miniforge3/bin/python3.10', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3504, 'min': 600, 'max': 3504}, 'cpu_freq_per_core': [{'current': 3504, 'min': 600, 'max': 3504}], 'disk': {'/': {'total': 460.4317207336426, 'used': 12.418434143066406}}, 'gpuapple': {'type': 'Apple M2', 'vendor': 'sppci_vendor_Apple'}, 'memory': {'total': 16.0}}
2024-08-30 20:38:53,942 INFO    HandlerThread:14510 [system_monitor.py:probe():224] Finished collecting system info
2024-08-30 20:38:53,942 INFO    HandlerThread:14510 [system_monitor.py:probe():227] Publishing system info
2024-08-30 20:38:53,942 DEBUG   HandlerThread:14510 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-08-30 20:38:53,998 INFO    Thread-12 :14510 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files/conda-environment.yaml
2024-08-30 20:38:56,007 INFO    Thread-12 :14510 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files/conda-environment.yaml
2024-08-30 20:38:56,051 DEBUG   HandlerThread:14510 [system_info.py:_save_conda():224] Saving conda packages done
2024-08-30 20:38:56,051 INFO    HandlerThread:14510 [system_monitor.py:probe():229] Finished publishing system info
2024-08-30 20:38:56,053 DEBUG   SenderThread:14510 [sender.py:send():391] send: files
2024-08-30 20:38:56,053 INFO    SenderThread:14510 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2024-08-30 20:38:56,123 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: python_packages
2024-08-30 20:38:56,123 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: python_packages
2024-08-30 20:38:56,123 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:38:56,123 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:38:56,124 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:38:56,127 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: pause
2024-08-30 20:38:56,127 INFO    HandlerThread:14510 [handler.py:handle_request_pause():728] stopping system metrics thread
2024-08-30 20:38:56,127 INFO    HandlerThread:14510 [system_monitor.py:finish():203] Stopping system monitor
2024-08-30 20:38:56,127 DEBUG   SystemMonitor:14510 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-30 20:38:56,127 DEBUG   SystemMonitor:14510 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-30 20:38:56,127 DEBUG   SystemMonitor:14510 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-30 20:38:56,127 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined cpu monitor
2024-08-30 20:38:56,127 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined disk monitor
2024-08-30 20:38:56,228 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined gpuapple monitor
2024-08-30 20:38:56,228 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined memory monitor
2024-08-30 20:38:56,228 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined network monitor
2024-08-30 20:38:56,835 DEBUG   SenderThread:14510 [sender.py:send():391] send: telemetry
2024-08-30 20:38:56,835 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:38:56,835 DEBUG   SenderThread:14510 [sender.py:send():391] send: telemetry
2024-08-30 20:38:56,836 DEBUG   SenderThread:14510 [sender.py:send():391] send: stats
2024-08-30 20:38:57,015 INFO    Thread-12 :14510 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files/wandb-metadata.json
2024-08-30 20:38:57,016 INFO    Thread-12 :14510 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files/requirements.txt
2024-08-30 20:38:57,465 INFO    wandb-upload_0:14510 [upload_job.py:push():130] Uploaded file /var/folders/bv/yrtwvfc92bnc90b_s89_h8280000gn/T/tmplj1paz9iwandb/shm7rfnt-wandb-metadata.json
2024-08-30 20:39:02,131 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:39:06,130 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:39:07,136 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:39:11,128 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:39:11,129 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:39:11,479 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: resume
2024-08-30 20:39:11,480 INFO    HandlerThread:14510 [handler.py:handle_request_resume():719] starting system metrics thread
2024-08-30 20:39:11,480 INFO    HandlerThread:14510 [system_monitor.py:start():194] Starting system monitor
2024-08-30 20:39:11,480 INFO    SystemMonitor:14510 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-30 20:39:11,481 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started cpu monitoring
2024-08-30 20:39:11,482 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started disk monitoring
2024-08-30 20:39:11,484 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started gpuapple monitoring
2024-08-30 20:39:11,485 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started memory monitoring
2024-08-30 20:39:11,491 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started network monitoring
2024-08-30 20:39:11,733 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: pause
2024-08-30 20:39:11,734 INFO    HandlerThread:14510 [handler.py:handle_request_pause():728] stopping system metrics thread
2024-08-30 20:39:11,734 INFO    HandlerThread:14510 [system_monitor.py:finish():203] Stopping system monitor
2024-08-30 20:39:11,734 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined cpu monitor
2024-08-30 20:39:11,735 DEBUG   SystemMonitor:14510 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-30 20:39:11,735 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined disk monitor
2024-08-30 20:39:11,735 DEBUG   SystemMonitor:14510 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-30 20:39:11,735 DEBUG   SystemMonitor:14510 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-30 20:39:11,789 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined gpuapple monitor
2024-08-30 20:39:11,789 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined memory monitor
2024-08-30 20:39:11,789 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined network monitor
2024-08-30 20:39:11,789 DEBUG   SenderThread:14510 [sender.py:send():391] send: stats
2024-08-30 20:39:12,795 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:39:16,135 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:39:18,150 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:39:23,162 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:39:24,141 INFO    Thread-12 :14510 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files/config.yaml
2024-08-30 20:39:26,133 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:39:26,134 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:39:26,139 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:39:28,983 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:39:34,159 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:39:36,144 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:39:37,098 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: resume
2024-08-30 20:39:37,098 INFO    HandlerThread:14510 [handler.py:handle_request_resume():719] starting system metrics thread
2024-08-30 20:39:37,098 INFO    HandlerThread:14510 [system_monitor.py:start():194] Starting system monitor
2024-08-30 20:39:37,098 INFO    SystemMonitor:14510 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-30 20:39:37,099 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started cpu monitoring
2024-08-30 20:39:37,103 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started disk monitoring
2024-08-30 20:39:37,103 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started gpuapple monitoring
2024-08-30 20:39:37,114 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started memory monitoring
2024-08-30 20:39:37,116 INFO    SystemMonitor:14510 [interfaces.py:start():188] Started network monitoring
2024-08-30 20:39:37,155 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: pause
2024-08-30 20:39:37,156 INFO    HandlerThread:14510 [handler.py:handle_request_pause():728] stopping system metrics thread
2024-08-30 20:39:37,156 INFO    HandlerThread:14510 [system_monitor.py:finish():203] Stopping system monitor
2024-08-30 20:39:37,156 DEBUG   SystemMonitor:14510 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-30 20:39:37,156 DEBUG   SystemMonitor:14510 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-30 20:39:37,156 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined cpu monitor
2024-08-30 20:39:37,156 DEBUG   SystemMonitor:14510 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-30 20:39:37,156 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined disk monitor
2024-08-30 20:39:37,430 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined gpuapple monitor
2024-08-30 20:39:37,430 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined memory monitor
2024-08-30 20:39:37,430 INFO    HandlerThread:14510 [interfaces.py:finish():200] Joined network monitor
2024-08-30 20:39:37,430 DEBUG   SenderThread:14510 [sender.py:send():391] send: stats
2024-08-30 20:39:39,440 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:39:41,136 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:39:41,137 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:39:44,910 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:39:46,146 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:39:50,180 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:39:56,138 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:39:56,139 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:39:56,150 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:39:56,743 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:02,173 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:06,155 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:40:07,180 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:11,144 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:40:11,145 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:40:12,533 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:16,160 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:40:18,191 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:23,199 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:26,145 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:40:26,146 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:40:26,165 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:40:28,532 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:34,208 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:36,166 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:40:40,212 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:41,150 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:40:41,151 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:40:45,615 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:46,167 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:40:51,208 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:40:56,155 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:40:56,157 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:40:56,172 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:40:56,525 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:02,218 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:06,175 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:41:07,219 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:11,158 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:41:11,159 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:41:12,568 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:16,177 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:41:18,228 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:23,229 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:26,159 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:41:26,160 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:41:26,178 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:41:28,509 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:34,236 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:36,179 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:41:39,246 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:41,164 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:41:41,165 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:41:44,476 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:46,179 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:41:50,260 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:55,266 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:41:56,167 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:41:56,168 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:41:56,185 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:42:00,565 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:06,191 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:42:06,257 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:11,172 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:42:11,174 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:42:11,679 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:16,192 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:42:17,268 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:22,268 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:26,174 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:42:26,175 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:42:26,196 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:42:27,528 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:33,282 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:36,201 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:42:38,286 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:41,179 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:42:41,180 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:42:43,483 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:46,204 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:42:49,296 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:54,297 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:42:56,182 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:42:56,183 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:42:56,208 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:42:59,496 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:05,311 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:06,213 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:43:10,316 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:11,184 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:43:11,185 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:43:15,562 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:16,218 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:43:21,315 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:26,189 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:43:26,190 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:43:26,221 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:43:26,477 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:32,324 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:36,222 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:43:37,326 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:41,194 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:43:41,195 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:43:42,539 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:46,227 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:43:48,337 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:53,343 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:43:56,199 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:43:56,200 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:43:56,231 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:43:58,581 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:04,354 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:06,234 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:44:09,362 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:11,205 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:44:11,206 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:44:14,546 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:16,239 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:44:20,365 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:25,374 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:26,209 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:44:26,209 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:44:26,244 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:44:30,557 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:36,249 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:44:36,375 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:41,213 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:44:41,214 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:44:41,611 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:46,254 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:44:47,388 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:52,389 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:44:56,214 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:44:56,215 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:44:56,254 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:44:57,587 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:03,399 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:06,258 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:45:09,401 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:11,219 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:45:11,220 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:45:14,559 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:16,260 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:45:20,413 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:25,418 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:26,223 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:45:26,224 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:45:26,262 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:45:30,637 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:36,268 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:45:36,413 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:41,229 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:45:41,230 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:45:41,637 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:46,270 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:45:47,424 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:52,427 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:45:56,232 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:45:56,233 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:45:56,274 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:45:57,611 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:03,437 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:06,279 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:46:09,437 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:11,235 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:46:11,236 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:46:14,618 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:16,285 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:46:20,451 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:25,455 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:26,236 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:46:26,237 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:46:26,289 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:46:30,564 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:36,292 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:46:36,453 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:41,237 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:46:41,238 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:46:41,585 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:46,296 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:46:47,463 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:52,464 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:46:56,238 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:46:56,239 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:46:56,297 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:46:57,602 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:03,474 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:06,302 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:47:09,478 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:11,241 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:47:11,242 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:47:14,560 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:16,307 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:47:20,494 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:25,498 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:26,246 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:47:26,246 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:47:26,312 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:47:30,650 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:36,314 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:47:36,493 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:41,248 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:47:41,249 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:47:41,630 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:46,315 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:47:47,500 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:53,505 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:47:56,251 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:47:56,252 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:47:56,320 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:47:58,580 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:04,517 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:06,325 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:48:09,525 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:11,253 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:48:11,255 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:48:14,572 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:16,327 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:48:20,536 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:25,536 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:26,257 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:48:26,259 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:48:26,332 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:48:30,951 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:36,337 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:48:36,532 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:41,262 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:48:41,263 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:48:41,651 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:46,342 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:48:47,545 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:52,549 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:48:56,267 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:48:56,268 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:48:56,347 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:48:57,620 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:03,565 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:06,350 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:49:09,567 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:11,272 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:49:11,273 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:49:14,677 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:16,356 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:49:20,578 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:26,277 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:49:26,278 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:49:26,361 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:49:26,680 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:32,573 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:36,362 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:49:37,574 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:41,280 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:49:41,281 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:49:42,680 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:46,366 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:49:48,587 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:54,587 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:49:56,281 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:49:56,283 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:49:56,370 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:49:59,591 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:04,597 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:06,372 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:50:09,602 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:11,283 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:50:11,284 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:50:14,658 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:16,373 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:50:20,613 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:26,288 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:50:26,289 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:50:26,378 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:50:26,622 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:32,613 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:36,381 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:50:38,616 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:41,293 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:50:41,294 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:50:43,643 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:46,385 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:50:49,624 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:54,626 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:50:56,297 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:50:56,298 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:50:56,390 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:50:59,858 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:05,641 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:06,391 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:51:10,658 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:11,300 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:51:11,302 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:51:15,705 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:16,401 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:51:21,649 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:26,307 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:51:26,308 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:51:26,405 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:51:26,658 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:31,669 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:36,410 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:51:36,675 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:41,316 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:51:41,317 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:51:41,703 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:46,412 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:51:47,685 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:52,688 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:51:56,322 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:51:56,323 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:51:56,417 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:51:57,694 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:03,694 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:06,417 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:52:08,704 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:11,322 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:52:11,323 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:52:13,756 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:16,422 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:52:19,712 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:24,718 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:26,327 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:52:26,328 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:52:26,426 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:52:29,720 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:34,730 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:36,430 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:52:39,732 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:41,332 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:52:41,333 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:52:44,738 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:46,435 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:52:50,735 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:55,741 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:52:56,337 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:52:56,338 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:52:56,441 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:53:00,764 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:06,445 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:53:06,740 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:11,338 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:53:11,339 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:53:11,741 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:16,450 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:53:16,743 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:21,747 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:26,343 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:53:26,344 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:53:26,450 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:53:26,750 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:31,754 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:36,455 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:53:36,759 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:41,348 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:53:41,348 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:53:41,763 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:46,459 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:53:46,766 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:51,769 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:53:56,354 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:53:56,355 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:53:56,464 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:53:56,775 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:54:01,779 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:54:06,465 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:54:06,784 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:54:11,358 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:54:11,359 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:54:11,785 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:54:16,470 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:54:16,790 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:54:21,791 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:54:26,363 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:54:26,364 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:54:26,471 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:54:27,012 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:54:44,293 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:54:53,667 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:54:58,562 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:54:58,563 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:54:59,117 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:55:10,248 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:55:13,617 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:55:21,433 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:55:21,434 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:55:21,545 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:55:23,917 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:57:26,170 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:57:28,531 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:57:31,066 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:57:31,066 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:57:34,337 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:57:36,175 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:57:39,543 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:57:44,545 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:57:46,072 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:57:46,073 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:57:46,178 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:57:49,684 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:57:55,563 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:57:56,184 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:58:00,568 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:01,076 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:58:01,077 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:58:05,571 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:06,189 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:58:11,562 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:16,077 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:58:16,078 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:58:16,195 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:58:16,568 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:21,568 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:26,200 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:58:26,571 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:31,077 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:58:31,078 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:58:31,576 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:36,205 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:58:36,577 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:41,578 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:46,083 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:58:46,083 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:58:46,210 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:58:46,578 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:51,580 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:58:56,212 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:58:56,582 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:01,087 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:59:01,089 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:59:01,585 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:06,217 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:59:06,585 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:11,589 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:16,091 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:59:16,092 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:59:16,222 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:59:16,591 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:21,597 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:26,225 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:59:26,601 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:31,092 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:59:31,093 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:59:31,718 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:36,228 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:59:37,612 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:42,618 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:46,095 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 20:59:46,096 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 20:59:46,230 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 20:59:47,620 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 20:59:52,624 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 21:00:01,761 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 21:00:05,176 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 21:00:06,623 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 21:00:06,624 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 21:00:17,580 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 21:00:18,984 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 21:00:38,825 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 21:00:39,260 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 21:00:39,261 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 21:00:39,401 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 21:00:43,828 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 21:16:19,226 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 21:16:21,648 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 21:16:24,083 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 21:16:24,084 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 21:33:21,911 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 21:33:24,458 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-30 21:33:26,945 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-30 21:51:15,063 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-30 21:51:15,479 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 22:06:29,166 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-30 22:06:29,334 INFO    SenderThread:14510 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2024-08-30 22:21:43,776 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-30 22:21:44,670 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 22:38:48,540 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-30 22:56:05,853 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 23:00:03,884 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-30 23:00:05,969 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:00:06,775 INFO    Thread-12 :14510 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files/output.log
2024-08-30 23:00:08,335 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 23:00:08,609 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 23:00:08,610 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 23:00:08,793 INFO    Thread-12 :14510 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files/output.log
2024-08-30 23:00:11,047 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:17:36,927 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:17:39,212 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 23:34:49,703 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:34:52,071 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 23:34:52,072 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 23:34:54,844 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:41:00,812 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 23:41:05,565 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:41:10,779 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:41:10,907 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 23:41:11,174 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 23:41:11,175 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 23:41:16,666 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:42:31,592 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 23:42:34,470 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:42:56,836 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 23:42:56,836 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 23:42:59,372 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:43:01,496 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 23:45:06,792 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:45:11,806 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:45:13,907 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 23:45:14,248 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 23:45:14,249 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 23:45:17,268 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:47:55,553 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-30 23:47:58,473 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:52:36,001 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-30 23:52:36,002 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-30 23:52:38,861 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-30 23:52:40,590 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 00:03:06,350 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 00:03:07,420 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 00:03:07,891 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 00:03:07,892 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 00:03:09,612 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 00:03:11,893 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 00:14:15,507 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 00:14:19,446 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 00:27:24,140 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 00:27:24,141 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 00:27:28,488 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 00:39:46,191 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 00:39:52,106 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 00:39:52,145 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 00:39:52,792 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 00:39:52,793 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 00:39:57,747 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 00:49:42,441 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 00:49:46,396 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 00:49:48,079 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 00:49:48,080 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 01:01:56,679 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 01:01:57,539 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 01:01:59,655 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 01:13:41,003 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 01:13:42,010 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 01:13:42,651 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 01:13:42,653 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 01:13:46,517 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 01:25:45,994 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 01:25:50,002 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 01:25:51,636 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 01:25:51,637 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 01:42:07,001 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 01:58:20,751 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 02:14:30,383 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 02:32:08,083 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 02:48:00,592 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 03:05:27,398 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 03:05:31,843 INFO    SenderThread:14510 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2024-08-31 03:20:40,823 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 03:38:05,781 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 03:38:10,439 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 03:54:37,075 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 04:12:04,652 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 04:26:20,388 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 04:43:51,513 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 04:43:51,969 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 04:43:54,388 INFO    Thread-12 :14510 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files/output.log
2024-08-31 05:17:39,737 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 05:17:40,304 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 05:17:40,898 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 05:17:40,899 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 05:35:33,907 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 05:35:37,336 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 05:53:20,374 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 06:08:52,531 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 06:08:52,985 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 06:41:02,715 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 06:41:05,696 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 06:41:07,143 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 06:41:07,144 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 06:45:18,689 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 06:45:23,892 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 06:45:24,336 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 06:45:25,305 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 07:02:58,701 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 07:02:58,702 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 07:19:16,876 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 07:19:18,804 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 07:34:55,434 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 07:51:13,034 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 07:51:14,908 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 07:51:16,354 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 07:51:16,355 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 08:07:00,617 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 08:24:04,044 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 08:24:15,727 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 08:24:20,543 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 08:41:23,589 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 08:46:20,767 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 08:46:25,986 INFO    SenderThread:14510 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2024-08-31 08:46:26,256 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 09:03:16,685 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 09:03:17,799 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 09:03:20,802 INFO    Thread-12 :14510 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files/output.log
2024-08-31 09:20:29,037 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 09:20:30,126 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 09:20:30,127 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 09:20:33,277 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 09:38:29,615 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 09:47:17,899 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 09:47:21,374 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 09:47:22,911 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 09:47:23,226 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 09:47:23,227 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 09:47:28,051 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 10:05:17,526 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 10:22:23,631 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 10:22:24,940 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 10:22:24,941 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 10:22:28,172 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 10:22:28,655 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 10:48:17,815 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 10:48:21,339 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 10:48:23,110 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 10:48:23,112 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 10:48:25,061 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 11:06:15,633 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 11:06:16,163 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 11:07:17,393 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 11:07:18,678 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 11:07:18,679 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 11:07:21,916 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 11:07:22,747 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 11:23:37,789 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 11:40:21,919 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 11:40:23,682 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 11:40:23,683 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 11:49:18,845 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 11:49:24,013 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 11:49:24,526 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 12:00:06,051 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 12:00:06,327 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 12:00:06,328 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 12:17:38,992 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 12:33:12,554 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 12:39:17,120 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 12:39:22,183 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 12:39:23,238 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 12:39:27,118 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 12:50:23,543 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 12:50:23,918 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 12:50:23,919 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 12:51:03,416 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 12:51:08,089 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 12:51:15,891 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 12:51:17,938 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 12:51:17,939 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 12:51:18,563 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 12:51:23,568 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 12:51:25,887 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 12:51:28,678 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 12:51:33,043 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 12:51:33,044 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 12:51:33,683 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 12:52:05,037 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 12:52:09,736 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 12:52:31,619 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 12:52:34,560 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 12:52:36,600 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 12:52:36,601 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 12:52:41,674 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:10:15,411 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:10:19,850 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 13:10:30,321 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:10:31,640 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:10:31,641 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:10:34,661 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:10:35,449 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:10:41,352 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:11:09,643 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:11:11,621 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:11:11,622 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:11:14,323 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:11:19,325 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:11:19,643 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:13:57,995 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:13:58,276 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:13:58,277 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:18:23,029 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 13:18:23,306 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:18:28,327 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 13:22:55,181 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:23:00,533 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 13:23:05,190 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:23:05,860 INFO    SenderThread:14510 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2024-08-31 13:28:32,603 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 13:28:33,358 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:28:34,557 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:28:34,558 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:35:41,758 INFO    Thread-12 :14510 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/meinv/Downloads/d2l-zh/pytorch/chapter_multilayer-perceptrons/wandb/run-20240830_203851-d9osfep0/files/output.log
2024-08-31 13:35:42,817 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:35:47,677 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:40:05,144 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:40:07,000 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:40:07,480 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:40:07,481 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:40:08,583 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 6, 'content': ['ERROR 2024-08-31T05:28:35.592295 wandb: Network error (SSLError), entering retry loop.\n', 'ERROR 2024-08-31T05:28:35.592295 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Network error resolved after 0:14:35.078064, resuming normal operation.\n']}}, 'dropped': 0}}
2024-08-31 13:40:12,498 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:40:15,160 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:44:30,742 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:44:31,193 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:44:31,194 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:44:33,869 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:44:36,361 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:51:17,978 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:51:20,128 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:51:22,452 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:51:22,453 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:51:24,441 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:51:30,002 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:51:30,134 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:55:56,551 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:55:57,000 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:55:57,001 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:55:59,672 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:56:02,062 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:56:07,552 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:56:09,674 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:56:12,004 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:56:12,005 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:56:12,557 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:56:17,562 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:56:19,679 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:56:32,145 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:56:32,146 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:56:32,439 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:56:34,827 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:56:37,713 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:56:42,717 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:56:44,830 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:56:47,146 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:56:47,148 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:56:47,718 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:56:52,720 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:56:54,834 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:56:57,725 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:57:02,148 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:57:02,149 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:57:02,732 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:57:04,835 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:57:07,741 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:57:12,741 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:57:14,844 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:57:17,155 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:57:17,155 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:57:17,741 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:57:22,747 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:57:24,852 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:57:27,756 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:57:32,165 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 13:57:32,166 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 13:57:32,764 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 13:57:34,854 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 13:57:37,769 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: status_report
2024-08-31 14:05:29,758 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:05:32,061 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: stop_status
2024-08-31 14:05:32,061 DEBUG   SenderThread:14510 [sender.py:send_request():418] send_request: stop_status
2024-08-31 14:05:37,710 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:05:38,728 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x105a9b7c0>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)")). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 14:05:39,766 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:05:40,783 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x107c15510>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)")). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 14:14:56,609 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:14:57,237 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x107c15900>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)")). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 14:15:01,536 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:15:05,337 INFO    SenderThread:14510 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/meinv/miniforge3/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x107c16a70>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x107c16a70>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/meinv/miniforge3/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x107c16a70>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-31 14:15:05,829 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x107c16800>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)")). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 14:15:06,646 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:15:11,540 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:15:16,693 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:15:21,544 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:15:23,196 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x107c15b10>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)")). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 14:15:26,724 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:15:31,545 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:15:36,781 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:15:41,555 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:15:46,835 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:15:51,565 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:15:56,409 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x107c15f90>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)")). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 14:15:56,917 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:16:01,572 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:17:51,052 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:17:55,646 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:18:53,377 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:18:57,813 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:19:03,411 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:19:07,817 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:19:13,445 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:19:17,823 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:19:23,479 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:19:27,827 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:19:33,514 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:19:37,828 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:19:43,552 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:19:47,830 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:19:49,381 WARNING FileStreamThread:14510 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/teriii/kaggle_california/d9osfep0/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x107c149a0>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)")). func: <bound method Session.post of <requests.sessions.Session object at 0x105a5e9e0>>, args: ('https://api.wandb.ai/files/teriii/kaggle_california/d9osfep0/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-08-31 14:19:53,595 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:19:57,835 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:20:03,626 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:20:07,841 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:20:13,650 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:20:17,844 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:20:22,854 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:20:27,849 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:20:32,895 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:20:37,854 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:20:42,922 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:20:47,859 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:20:52,956 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:20:57,864 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:21:02,989 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:21:07,867 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:21:12,871 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:21:17,870 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:21:22,907 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:21:27,875 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:21:32,947 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:21:37,876 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:21:42,980 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:21:47,881 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:21:53,018 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
2024-08-31 14:21:57,881 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-31 14:22:03,059 DEBUG   HandlerThread:14510 [handler.py:handle_request():158] handle_request: keepalive
